### PR TITLE
Project Setup, Login, Signup UI Feature Merge in main

### PR DESCRIPTION
**Pull request by abhi-s7**
### Merging the following Features

1. Flutter Project Setup
2. Login UI Page
3. Signup UI Page

### Code Review changes - By Kranti

Removed unnecessary commented code

### CODE REVIEW

**Review by kranthijella — APPROVED** [review]

**Comment by swatkat20** [comment]
Looks good

**Review by swatkat20 — APPROVED** [review]
Make sure to check in the logo separately too, if it might be used somewhere else in the future we should be able to find it

**Review by swatkat20 — APPROVED** [review]

**Review by swatkat20 — APPROVED** [review]

**Review by HanSolo-P — COMMENTED** [review]
Can you please add comments to the code , so that when others see it will be easy to understand.

**Comment by abhi-s7** [comment]
> Can you please add comments to the code , so that when others see it will be easy to understand.
We already have an assets folder under the main project directory. The logo.png file is added there.

**Comment by abhi-s7** [comment]
I have added the comments and committed the updated code.

All the code reviews are being taken care of.

**Review by saimadhavarao — APPROVED** [review]
Everything is good to go.

**Pull request merged**
